// Bundle the built frontend (../frontend/dist) into the Worker.
//
// Each file becomes a Data module (copied as .static/files/<n>.bin — wrangler's
// default rules import *.bin as an ArrayBuffer) and .static/manifest.ts maps URL
// paths to {body, type, etag}. Code and frontend then ship as ONE atomic
// `wrangler deploy` (rollbacks included) and deploys only need the regular API
// token — Workers Static Assets uploads need a separate upload JWT.
//
//   node scripts/embed-static.mjs [distDir]
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync, copyFileSync } from "node:fs";
import { dirname, extname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const dist = process.argv[2] ?? join(root, "..", "frontend", "dist");
const out = join(root, ".static");

const TYPES = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json",
  ".webmanifest": "application/manifest+json",
  ".txt": "text/plain; charset=utf-8",
  ".xml": "application/xml",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".webp": "image/webp",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
};

function walk(dir) {
  return readdirSync(dir)
    .sort()
    .flatMap((name) => {
      const p = join(dir, name);
      return statSync(p).isDirectory() ? walk(p) : [p];
    });
}

rmSync(out, { recursive: true, force: true });
mkdirSync(join(out, "files"), { recursive: true });

const files = existsSync(dist) ? walk(dist) : [];
if (!files.length) {
  console.warn(`embed-static: no build found at ${dist} — run \`npm run build\` (serving an empty site)`);
}

const imports = [];
const entries = [];
let total = 0;
files.forEach((file, i) => {
  const urlPath = "/" + relative(dist, file).split(sep).join("/");
  const data = readFileSync(file);
  total += data.length;
  copyFileSync(file, join(out, "files", `${i}.bin`));
  const etag = `"${createHash("sha256").update(data).digest("hex").slice(0, 32)}"`;
  const type = TYPES[extname(file).toLowerCase()] ?? "application/octet-stream";
  imports.push(`import f${i} from "./files/${i}.bin";`);
  entries.push(`  ${JSON.stringify(urlPath)}: { body: f${i}, type: ${JSON.stringify(type)}, etag: ${JSON.stringify(etag)} },`);
});

writeFileSync(
  join(out, "manifest.ts"),
  `// GENERATED by scripts/embed-static.mjs from the frontend build — do not edit.\n` +
    `${imports.join("\n")}\n\n` +
    `export interface StaticFile {\n  body: ArrayBuffer;\n  type: string;\n  etag: string;\n}\n\n` +
    `export const STATIC: Record<string, StaticFile> = {\n${entries.join("\n")}\n};\n`,
);
console.log(`embed-static: ${files.length} files, ${(total / 1048576).toFixed(2)} MB from ${relative(root, dist) || dist}`);
