"""export stencil_url

Revision ID: 25ee7e4b5d11
Revises: a43d0cbe2b59
Create Date: 2026-06-10 10:00:46.926658
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25ee7e4b5d11'
down_revision: str | None = 'a43d0cbe2b59'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stencil_url', sa.String(length=1024), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.drop_column('stencil_url')

    # ### end Alembic commands ###
