"""user referred_by

Revision ID: c63b853aa9b4
Revises: f94e8e95b10d
Create Date: 2026-06-09 19:54:54.796664
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c63b853aa9b4'
down_revision: str | None = 'f94e8e95b10d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referred_by', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_referred_by'), ['referred_by'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_referred_by'))
        batch_op.drop_column('referred_by')

    # ### end Alembic commands ###
