"""usage ledger

Revision ID: ae5676a58114
Revises: cb1fc3d50ecc
Create Date: 2026-06-09 18:39:50.531971
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae5676a58114'
down_revision: str | None = 'cb1fc3d50ecc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_ledger',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('design_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_ledger_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_ledger_design_id'), ['design_id'], unique=False)
        batch_op.create_index('ix_usage_ledger_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_ledger_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_ledger_user_id'))
        batch_op.drop_index('ix_usage_ledger_user_created')
        batch_op.drop_index(batch_op.f('ix_usage_ledger_design_id'))
        batch_op.drop_index(batch_op.f('ix_usage_ledger_created_at'))

    op.drop_table('usage_ledger')
    # ### end Alembic commands ###
