"""capture design + placement

Revision ID: a43d0cbe2b59
Revises: b34e7feb5b38
Create Date: 2026-06-09 20:31:09.255006
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a43d0cbe2b59'
down_revision: str | None = 'b34e7feb5b38'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capture_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('design_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('x_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('y_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('scale', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rotation', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capture_sessions', schema=None) as batch_op:
        batch_op.drop_column('rotation')
        batch_op.drop_column('scale')
        batch_op.drop_column('y_pct')
        batch_op.drop_column('x_pct')
        batch_op.drop_column('design_id')

    # ### end Alembic commands ###
