"""mockups

Revision ID: f94e8e95b10d
Revises: 3b206dab5adf
Create Date: 2026-06-09 19:10:40.316596
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94e8e95b10d'
down_revision: str | None = '3b206dab5adf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mockups',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('design_id', sa.String(length=32), nullable=True),
    sa.Column('output_url', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mockups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mockups_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mockups_design_id'), ['design_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mockups_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mockups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mockups_user_id'))
        batch_op.drop_index(batch_op.f('ix_mockups_design_id'))
        batch_op.drop_index(batch_op.f('ix_mockups_created_at'))

    op.drop_table('mockups')
    # ### end Alembic commands ###
