"""user brand_name

Revision ID: b34e7feb5b38
Revises: c63b853aa9b4
Create Date: 2026-06-09 20:11:38.258010
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b34e7feb5b38'
down_revision: str | None = 'c63b853aa9b4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_name', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('brand_name')

    # ### end Alembic commands ###
