"""baseline schema

Revision ID: cb1fc3d50ecc
Revises: 
Create Date: 2026-06-09 18:30:10.814348
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb1fc3d50ecc'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('google_sub', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_google_sub'), ['google_sub'], unique=True)

    op.create_table('body_photos',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('storage_ref', sa.String(length=1024), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('body_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_body_photos_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_photos_user_id'), ['user_id'], unique=False)

    op.create_table('designs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('enhanced_prompt', sa.Text(), nullable=True),
    sa.Column('styles', sa.JSON(), nullable=False),
    sa.Column('modifiers', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('clean_png_url', sa.String(length=1024), nullable=True),
    sa.Column('thumb_url', sa.String(length=1024), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('parent_design_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_design_id'], ['designs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('designs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_designs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_designs_parent_design_id'), ['parent_design_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_designs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_designs_user_id'), ['user_id'], unique=False)

    op.create_table('capture_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('body_photo_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['body_photo_id'], ['body_photos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('capture_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capture_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_capture_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('previews',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('design_id', sa.String(length=32), nullable=False),
    sa.Column('body_photo_id', sa.String(length=32), nullable=False),
    sa.Column('x_pct', sa.Float(), nullable=False),
    sa.Column('y_pct', sa.Float(), nullable=False),
    sa.Column('scale', sa.Float(), nullable=False),
    sa.Column('rotation', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('output_url', sa.String(length=1024), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['body_photo_id'], ['body_photos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('previews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_previews_body_photo_id'), ['body_photo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_previews_design_id'), ['design_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_previews_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_previews_status'), ['status'], unique=False)

    op.create_table('exports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('design_id', sa.String(length=32), nullable=False),
    sa.Column('preview_id', sa.String(length=32), nullable=True),
    sa.Column('hires_url', sa.String(length=1024), nullable=True),
    sa.Column('mockup_url', sa.String(length=1024), nullable=True),
    sa.Column('watermarked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['preview_id'], ['previews.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exports_design_id'), ['design_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exports_design_id'))

    op.drop_table('exports')
    with op.batch_alter_table('previews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_previews_status'))
        batch_op.drop_index(batch_op.f('ix_previews_expires_at'))
        batch_op.drop_index(batch_op.f('ix_previews_design_id'))
        batch_op.drop_index(batch_op.f('ix_previews_body_photo_id'))

    op.drop_table('previews')
    with op.batch_alter_table('capture_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capture_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_capture_sessions_expires_at'))

    op.drop_table('capture_sessions')
    with op.batch_alter_table('designs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_designs_user_id'))
        batch_op.drop_index(batch_op.f('ix_designs_status'))
        batch_op.drop_index(batch_op.f('ix_designs_parent_design_id'))
        batch_op.drop_index(batch_op.f('ix_designs_created_at'))

    op.drop_table('designs')
    with op.batch_alter_table('body_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_body_photos_user_id'))
        batch_op.drop_index(batch_op.f('ix_body_photos_expires_at'))

    op.drop_table('body_photos')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_sub'))

    op.drop_table('users')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_events_action'))

    op.drop_table('events')
    # ### end Alembic commands ###
