export type MagicPrompt = { prompt: string; slug: string };

// "I'm feeling magic" inspiration pool (529 ideas). Expanded via the author-magic-prompts workflow.
export const MAGIC: MagicPrompt[] = [
  { prompt: "a wolf howling at a crescent moon", slug: "fine-line" },
  { prompt: "a blooming peony in full detail", slug: "japanese-irezumi" },
  { prompt: "a snake coiled around a dagger", slug: "american-traditional" },
  { prompt: "an intricate sacred-geometry mandala", slug: "mandala" },
  { prompt: "an astronaut drifting among stars", slug: "illustrative" },
  { prompt: "a flaming sacred heart", slug: "sailor-jerry" },
  { prompt: "a minimalist mountain range", slug: "minimalist" },
  { prompt: "a moth with detailed wings", slug: "dotwork-stippling" },
  { prompt: "a glowing cyber-sigil rune", slug: "cyber-sigilism" },
  { prompt: "lone wolf howling at full moon", slug: "black-and-grey-realism" },
  { prompt: "sleeping fox curled around its tail", slug: "fine-line" },
  { prompt: "coiled snake striking with bared fangs", slug: "american-traditional" },
  { prompt: "snow leopard prowling across jagged peaks", slug: "realism" },
  { prompt: "grizzly bear roaring beneath pine forest", slug: "neo-traditional" },
  { prompt: "stag with antlers branching into trees", slug: "linework" },
  { prompt: "swallow carrying a banner in flight", slug: "sailor-jerry" },
  { prompt: "great horned owl perched on bone", slug: "dotwork-stippling" },
  { prompt: "octopus tentacles wrapping a sunken anchor", slug: "japanese-irezumi" },
  { prompt: "koi swimming upstream against rushing current", slug: "japanese-irezumi" },
  { prompt: "great white shark rising from depths", slug: "3d-realism" },
  { prompt: "honeybee hovering above clover blossom", slug: "micro-tiny" },
  { prompt: "monarch butterfly with translucent wings spread", slug: "watercolor" },
  { prompt: "spider descending on a single thread", slug: "single-needle" },
  { prompt: "dragon curling through storm clouds", slug: "japanese-irezumi" },
  { prompt: "panther crouched ready to pounce", slug: "chicano-fineline-bng" },
  { prompt: "raven with wings spread wide", slug: "blackwork" },
  { prompt: "hummingbird sipping from trumpet flower", slug: "fine-line" },
  { prompt: "seahorse drifting among coral fronds", slug: "illustrative" },
  { prompt: "phoenix rising from scattered embers", slug: "neo-traditional" },
  { prompt: "leaping rabbit through tall meadow grass", slug: "minimalist" },
  { prompt: "bull elephant with raised trunk trumpeting", slug: "engraving-woodcut" },
  { prompt: "scarab beetle with iridescent shell", slug: "ornamental-filigree" },
  { prompt: "barn owl mid-flight clutching mouse", slug: "portrait" },
  { prompt: "humpback whale breaching the surface", slug: "illustrative" },
  { prompt: "tiger head framed by bamboo leaves", slug: "japanese-irezumi" },
  { prompt: "crow standing on a weathered skull", slug: "ignorant-style" },
  { prompt: "jellyfish trailing glowing tentacles downward", slug: "watercolor" },
  { prompt: "praying mantis poised on a branch", slug: "linework" },
  { prompt: "wolf skull entwined with wildflowers", slug: "sketch-scribble" },
  { prompt: "soaring eagle gripping a thunderbolt", slug: "american-traditional" },
  { prompt: "kraken dragging a ship under waves", slug: "trash-polka" },
  { prompt: "lioness nuzzling her sleeping cub", slug: "black-and-grey-realism" },
  { prompt: "cobra hood flared over geometric pattern", slug: "geometric" },
  { prompt: "deer skull crowned with celestial stars", slug: "celestial-astro" },
  { prompt: "moth with skull marking on wings", slug: "dotwork-stippling" },
  { prompt: "fox curled inside a crescent moon", slug: "fine-line" },
  { prompt: "dragonfly hovering over still pond", slug: "single-needle" },
  { prompt: "bear paw print filled with mountains", slug: "minimalist" },
  { prompt: "winged griffin guarding ancient ruins", slug: "engraving-woodcut" },
  { prompt: "manta ray gliding through open ocean", slug: "illustrative" },
  { prompt: "rooster strutting with flared tail feathers", slug: "american-traditional" },
  { prompt: "lynx face emerging from shadow", slug: "realism" },
  { prompt: "two koi circling in yin-yang", slug: "japanese-irezumi" },
  { prompt: "horned beetle locked in fierce combat", slug: "blackwork" },
  { prompt: "cardinal perched on snowy branch", slug: "neo-traditional" },
  { prompt: "serpent devouring its own tail", slug: "ornamental-filigree" },
  { prompt: "leopard gecko clinging to desert stone", slug: "illustrative" },
  { prompt: "flock of starlings forming a wave", slug: "abstract" },
  { prompt: "hammerhead shark patrolling the reef", slug: "linework" },
  { prompt: "stag beetle rendered in fractured panels", slug: "trash-polka" },
  { prompt: "barn swallow diving through open sky", slug: "micro-tiny" },
  { prompt: "wolf head splitting into glitching pixels", slug: "glitch" },
  { prompt: "peacock fanning its jeweled tail", slug: "ornamental-filigree" },
  { prompt: "scorpion arched with stinger raised", slug: "tribal" },
  { prompt: "owl perched within a blooming mandala", slug: "mandala" },
  { prompt: "single rose with a curling stem", slug: "fine-line" },
  { prompt: "blooming peony in full layered petals", slug: "japanese-irezumi" },
  { prompt: "scattered wildflowers across a meadow", slug: "watercolor" },
  { prompt: "a sprig of olive branch and leaves", slug: "single-needle" },
  { prompt: "unfurling fern frond", slug: "linework" },
  { prompt: "ancient oak tree with sprawling roots", slug: "black-and-grey-realism" },
  { prompt: "cluster of fly agaric mushrooms", slug: "neo-traditional" },
  { prompt: "trailing ivy vines wrapping a forearm", slug: "blackwork" },
  { prompt: "bundle of dried lavender stalks", slug: "micro-tiny" },
  { prompt: "sacred lotus rising from water", slug: "ornamental-filigree" },
  { prompt: "potted echeveria succulent rosette", slug: "illustrative" },
  { prompt: "tied bouquet of garden flowers", slug: "sketch-scribble" },
  { prompt: "thorny rose framed in geometry", slug: "geometric" },
  { prompt: "lotus opening into a mandala", slug: "mandala" },
  { prompt: "tiny forget-me-not blossoms", slug: "micro-tiny" },
  { prompt: "morel mushroom on a forest floor", slug: "realism" },
  { prompt: "monstera leaf with split fronds", slug: "minimalist" },
  { prompt: "wild poppy nodding on its stem", slug: "american-traditional" },
  { prompt: "weeping willow over still water", slug: "japanese-irezumi" },
  { prompt: "sprig of rosemary herb", slug: "fine-line" },
  { prompt: "dandelion releasing its seeds", slug: "dotwork-stippling" },
  { prompt: "cherry blossom branch in bloom", slug: "japanese-irezumi" },
  { prompt: "cactus blooming in the desert", slug: "new-school" },
  { prompt: "ring of laurel leaves crown", slug: "engraving-woodcut" },
  { prompt: "venus flytrap with open jaws", slug: "trash-polka" },
  { prompt: "sunflower turning toward light", slug: "neo-traditional" },
  { prompt: "twisting grapevine heavy with fruit", slug: "ornamental-filigree" },
  { prompt: "pressed pansy with delicate veins", slug: "watercolor" },
  { prompt: "wheat stalks bending in wind", slug: "linework" },
  { prompt: "magnolia bloom on a bare branch", slug: "black-and-grey-realism" },
  { prompt: "tangled bramble of blackberry thorns", slug: "ignorant-style" },
  { prompt: "string of pearls succulent trailing", slug: "single-needle" },
  { prompt: "iris flower with arching petals", slug: "neo-traditional" },
  { prompt: "pine tree against mountain ridge", slug: "minimalist" },
  { prompt: "cosmic flower blooming among stars", slug: "celestial-astro" },
  { prompt: "hellebore drooping in winter frost", slug: "realism" },
  { prompt: "bundle of sage smudge herbs", slug: "stick-and-poke" },
  { prompt: "tulip bud about to open", slug: "fine-line" },
  { prompt: "carnivorous pitcher plant hanging", slug: "illustrative" },
  { prompt: "lily of the valley stems", slug: "micro-tiny" },
  { prompt: "twin koi circling a lotus pond", slug: "japanese-irezumi" },
  { prompt: "thistle with spiked purple crown", slug: "blackwork" },
  { prompt: "honeysuckle vine with trumpet blooms", slug: "floral-botanical" },
  { prompt: "bonsai juniper shaped by wind", slug: "sketch-scribble" },
  { prompt: "ghostly white moon flowers at night", slug: "surrealism" },
  { prompt: "ranunculus layered like a rose", slug: "fine-line" },
  { prompt: "maple leaf turning in autumn", slug: "realism" },
  { prompt: "bell-shaped foxglove spire", slug: "neo-traditional" },
  { prompt: "saguaro cactus under desert sun", slug: "linework" },
  { prompt: "wisteria cascading in heavy clusters", slug: "watercolor" },
  { prompt: "anemone flower with dark center", slug: "black-and-grey-realism" },
  { prompt: "mushroom cluster glitching apart", slug: "glitch" },
  { prompt: "protea bloom with spiked petals", slug: "geometric" },
  { prompt: "snowdrop pushing through frozen ground", slug: "single-needle" },
  { prompt: "chrysanthemum opening in full glory", slug: "japanese-irezumi" },
  { prompt: "crescent moon cradling a tiny star", slug: "fine-line" },
  { prompt: "full moon over a still ocean", slug: "black-and-grey-realism" },
  { prompt: "Saturn with delicate orbiting rings", slug: "single-needle" },
  { prompt: "the eight phases of the moon", slug: "minimalist" },
  { prompt: "a comet streaking across the sky", slug: "illustrative" },
  { prompt: "spiral galaxy swirling into deep space", slug: "watercolor" },
  { prompt: "sun and moon entwined as lovers", slug: "ornamental-filigree" },
  { prompt: "Orion constellation traced in connected stars", slug: "dotwork-stippling" },
  { prompt: "astronaut drifting on a tether", slug: "realism" },
  { prompt: "total solar eclipse ring of fire", slug: "blackwork" },
  { prompt: "tiny shooting star behind the ear", slug: "micro-tiny" },
  { prompt: "radiant sun face with flowing rays", slug: "american-traditional" },
  { prompt: "Leo lion rising among zodiac stars", slug: "neo-traditional" },
  { prompt: "sacred geometry sun mandala", slug: "mandala" },
  { prompt: "hexagonal cluster of nested planets", slug: "geometric" },
  { prompt: "north star guiding a sailing ship", slug: "sailor-jerry" },
  { prompt: "moon goddess crowned with stars", slug: "japanese-irezumi" },
  { prompt: "three stacked moon phases in a row", slug: "linework" },
  { prompt: "a single five pointed star", slug: "stick-and-poke" },
  { prompt: "Saturn floating above an open palm", slug: "sketch-scribble" },
  { prompt: "galaxy bursting through a cracked skull", slug: "trash-polka" },
  { prompt: "constellation map of the night sky", slug: "engraving-woodcut" },
  { prompt: "crescent moon holding a sleeping cat", slug: "illustrative" },
  { prompt: "sun rising over mountain peaks", slug: "minimalist" },
  { prompt: "glowing planet wrapped in circuit veins", slug: "cyber-sigilism" },
  { prompt: "shattered moon splitting into pixels", slug: "glitch" },
  { prompt: "Scorpio scorpion beneath a red star", slug: "chicano-fineline-bng" },
  { prompt: "celestial eye weeping starlight", slug: "surrealism" },
  { prompt: "comet tail of falling flowers", slug: "floral-botanical" },
  { prompt: "the moon and sun in eclipse", slug: "celestial-astro" },
  { prompt: "tiny Saturn on the wrist", slug: "micro-tiny" },
  { prompt: "sun wearing a serene human face", slug: "sketch-scribble" },
  { prompt: "crescent moon pierced by an arrow", slug: "fine-line" },
  { prompt: "astronaut floating among jellyfish stars", slug: "new-school" },
  { prompt: "ringed planet orbited by tiny moons", slug: "dotwork-stippling" },
  { prompt: "full moon framed by reaching branches", slug: "linework" },
  { prompt: "Gemini twins beneath paired stars", slug: "neo-traditional" },
  { prompt: "swirling sun with curling solar flares", slug: "ornamental-filigree" },
  { prompt: "crescent moon resting on the collarbone", slug: "single-needle" },
  { prompt: "the Big Dipper across the forearm", slug: "minimalist" },
  { prompt: "meteor shower over a desert horizon", slug: "black-and-grey-realism" },
  { prompt: "sun and moon halves split down center", slug: "blackwork" },
  { prompt: "planet earth seen from the moon", slug: "realism" },
  { prompt: "crescent moon with a single dangling star", slug: "micro-tiny" },
  { prompt: "galaxy spiral inside a glass bottle", slug: "illustrative" },
  { prompt: "sun with rays of geometric triangles", slug: "geometric" },
  { prompt: "comet carving through a starfield", slug: "engraving-woodcut" },
  { prompt: "Saturn balanced on a stack of clouds", slug: "watercolor" },
  { prompt: "a row of three tiny stars", slug: "stick-and-poke" },
  { prompt: "lunar surface craters in close detail", slug: "3d-realism" },
  { prompt: "Sagittarius archer aiming at a star", slug: "american-traditional" },
  { prompt: "crescent moon woven with ivy vines", slug: "floral-botanical" },
  { prompt: "black hole bending rings of light", slug: "abstract" },
  { prompt: "astronaut helmet reflecting a nebula", slug: "realism" },
  { prompt: "the phrase per aspera ad astra", slug: "script-lettering" },
  { prompt: "coiled dragon clutching a flaming pearl", slug: "japanese-irezumi" },
  { prompt: "mermaid combing her hair on a rock", slug: "american-traditional" },
  { prompt: "tiny kitsune with three swishing tails", slug: "fine-line" },
  { prompt: "valkyrie carrying a fallen warrior skyward", slug: "black-and-grey-realism" },
  { prompt: "snarling oni mask with curved horns", slug: "japanese-irezumi" },
  { prompt: "bind rune circle of protection", slug: "blackwork" },
  { prompt: "red riding hood facing the wolf", slug: "illustrative" },
  { prompt: "Medusa with serpents framing her face", slug: "realism" },
  { prompt: "Thor's hammer wrapped in lightning", slug: "linework" },
  { prompt: "nine-tailed fox curled around the moon", slug: "dotwork-stippling" },
  { prompt: "siren luring sailors onto jagged cliffs", slug: "neo-traditional" },
  { prompt: "Anubis weighing a heart against a feather", slug: "blackwork" },
  { prompt: "Pegasus galloping across drifting clouds", slug: "watercolor" },
  { prompt: "kraken dragging a ship beneath waves", slug: "japanese-irezumi" },
  { prompt: "Yggdrasil tree connecting nine realms", slug: "ornamental-filigree" },
  { prompt: "minotaur prowling a stone labyrinth", slug: "black-and-grey-realism" },
  { prompt: "delicate fairy perched on a toadstool", slug: "fine-line" },
  { prompt: "Cerberus guarding the gates of the underworld", slug: "realism" },
  { prompt: "Norse raven Huginn mid-flight", slug: "linework" },
  { prompt: "selkie shedding her sealskin at dusk", slug: "illustrative" },
  { prompt: "tengu mask with a long crow beak", slug: "japanese-irezumi" },
  { prompt: "Valknut knot of the slain", slug: "geometric" },
  { prompt: "Baba Yaga's hut on chicken legs", slug: "sketch-scribble" },
  { prompt: "Athena's owl perched with spear", slug: "engraving-woodcut" },
  { prompt: "tiny winged Cupid drawing his bow", slug: "micro-tiny" },
  { prompt: "Quetzalcoatl feathered serpent descending", slug: "ornamental-filigree" },
  { prompt: "kitsune fox mask with floral accents", slug: "fine-line" },
  { prompt: "Fenrir wolf breaking its chains", slug: "blackwork" },
  { prompt: "Hydra sprouting three new heads", slug: "neo-traditional" },
  { prompt: "Persephone holding a split pomegranate", slug: "black-and-grey-realism" },
  { prompt: "dancing skeleton from a fairy tale", slug: "ignorant-style" },
  { prompt: "Egyptian goddess Isis with spread wings", slug: "ornamental-filigree" },
  { prompt: "thunderbird with outstretched storm wings", slug: "american-traditional" },
  { prompt: "small crescent moon spirit fox", slug: "single-needle" },
  { prompt: "leviathan sea serpent circling an anchor", slug: "japanese-irezumi" },
  { prompt: "Valhalla gates beneath crossed swords", slug: "engraving-woodcut" },
  { prompt: "banshee wailing in the mist", slug: "surrealism" },
  { prompt: "ouroboros serpent devouring its tail", slug: "dotwork-stippling" },
  { prompt: "Loki's face splitting into trickster grins", slug: "trash-polka" },
  { prompt: "Japanese koi transforming into a dragon", slug: "japanese-irezumi" },
  { prompt: "Valkyrie wings spanning the shoulder blades", slug: "ornamental-filigree" },
  { prompt: "the Morrigan as a battlefield crow", slug: "blackwork" },
  { prompt: "elder futhark rune row across the forearm", slug: "script-lettering" },
  { prompt: "Pan piping in a moonlit forest", slug: "illustrative" },
  { prompt: "tiny mermaid silhouette diving down", slug: "minimalist" },
  { prompt: "Hel ruling her shadowed realm", slug: "black-and-grey-realism" },
  { prompt: "golden phoenix feather drifting downward", slug: "fine-line" },
  { prompt: "Greek sphinx posing a riddle", slug: "engraving-woodcut" },
  { prompt: "Slavic firebird with blazing plumage", slug: "watercolor" },
  { prompt: "oni demon battling a tiny samurai", slug: "new-school" },
  { prompt: "moon goddess Selene driving her chariot", slug: "celestial-astro" },
  { prompt: "kelpie water horse rising from a loch", slug: "realism" },
  { prompt: "Odin's spear Gungnir crossed with ravens", slug: "linework" },
  { prompt: "Hansel and Gretel's candy cottage", slug: "illustrative" },
  { prompt: "twin daggers crossed through a blooming rose", slug: "american-traditional" },
  { prompt: "ornate dagger piercing a beating heart", slug: "neo-traditional" },
  { prompt: "a single thin dagger down the spine", slug: "fine-line" },
  { prompt: "broadsword wrapped in a coiling serpent", slug: "japanese-irezumi" },
  { prompt: "knight's longsword embedded in a stone", slug: "black-and-grey-realism" },
  { prompt: "crossed swords behind a feathered war helmet", slug: "blackwork" },
  { prompt: "tiny anchor with a delicate rope bow", slug: "micro-tiny" },
  { prompt: "heavy anchor tangled in ship rigging", slug: "sailor-jerry" },
  { prompt: "anchor wrapped in rope and roses", slug: "american-traditional" },
  { prompt: "a melting clock draped over a branch", slug: "surrealism" },
  { prompt: "antique mantel clock with roman numbers", slug: "realism" },
  { prompt: "broken clock spilling gears and cogs", slug: "trash-polka" },
  { prompt: "clock face dissolving into scattered birds", slug: "illustrative" },
  { prompt: "an open pocket watch on a chain", slug: "black-and-grey-realism" },
  { prompt: "pocket watch exposing intricate inner gears", slug: "biomechanical" },
  { prompt: "small pocket watch frozen at midnight", slug: "fine-line" },
  { prompt: "ornate skeleton key entwined with ivy", slug: "ornamental-filigree" },
  { prompt: "tiny vintage key on a thread", slug: "single-needle" },
  { prompt: "a key opening a winged padlock heart", slug: "neo-traditional" },
  { prompt: "cluster of antique keys on a ring", slug: "linework" },
  { prompt: "a dripping candle burning at both ends", slug: "american-traditional" },
  { prompt: "candle flame cradled by two hands", slug: "illustrative" },
  { prompt: "single lit candle in a brass holder", slug: "black-and-grey-realism" },
  { prompt: "melting candle beside an open spellbook", slug: "sketch-scribble" },
  { prompt: "an old railway lantern glowing softly", slug: "neo-traditional" },
  { prompt: "paper lantern drifting into the night", slug: "watercolor" },
  { prompt: "hanging oil lantern swarmed by moths", slug: "blackwork" },
  { prompt: "tiny lantern lighting a forest path", slug: "fine-line" },
  { prompt: "open book with pages turning into birds", slug: "illustrative" },
  { prompt: "stack of weathered leather-bound books", slug: "realism" },
  { prompt: "tiny open book with a pressed flower", slug: "micro-tiny" },
  { prompt: "ancient grimoire chained shut with locks", slug: "blackwork" },
  { prompt: "violin resting against sheet music", slug: "black-and-grey-realism" },
  { prompt: "acoustic guitar wreathed in wildflowers", slug: "neo-traditional" },
  { prompt: "grand piano keys curling into smoke", slug: "surrealism" },
  { prompt: "small treble clef and tiny notes", slug: "minimalist" },
  { prompt: "vintage trumpet entwined with roses", slug: "american-traditional" },
  { prompt: "old folding bellows camera on a tripod", slug: "realism" },
  { prompt: "tiny camera with a heart shutter", slug: "micro-tiny" },
  { prompt: "camera lens reflecting a mountain range", slug: "illustrative" },
  { prompt: "polaroid photo developing a memory", slug: "watercolor" },
  { prompt: "tall ship sailing across crashing waves", slug: "japanese-irezumi" },
  { prompt: "clipper ship bursting through a storm", slug: "american-traditional" },
  { prompt: "tiny sailboat on a single wave line", slug: "minimalist" },
  { prompt: "ghostly galleon wreathed in fog", slug: "black-and-grey-realism" },
  { prompt: "fine-line schooner with three masts", slug: "linework" },
  { prompt: "vintage biplane trailing looping smoke", slug: "neo-traditional" },
  { prompt: "paper airplane gliding over rooftops", slug: "single-needle" },
  { prompt: "fighter plane diving through clouds", slug: "american-traditional" },
  { prompt: "tiny airplane circling a small globe", slug: "micro-tiny" },
  { prompt: "compass rose and crossed anchors", slug: "dotwork-stippling" },
  { prompt: "hourglass leaking sand into a rose", slug: "neo-traditional" },
  { prompt: "ship's wheel framed by ocean waves", slug: "blackwork" },
  { prompt: "an antique typewriter spelling a single word", slug: "illustrative" },
  { prompt: "brass telescope aimed at the stars", slug: "celestial-astro" },
  { prompt: "ornate hand mirror reflecting a moon", slug: "ornamental-filigree" },
  { prompt: "interlocking circles forming flower of life", slug: "geometric" },
  { prompt: "all-seeing eye inside radiant triangle", slug: "dotwork-stippling" },
  { prompt: "two hands clasped in quiet prayer", slug: "black-and-grey-realism" },
  { prompt: "open palm hamsa with centered eye", slug: "ornamental-filigree" },
  { prompt: "blue glass evil eye bead", slug: "fine-line" },
  { prompt: "seven glowing chakra points along spine", slug: "dotwork-stippling" },
  { prompt: "small cross resting on collarbone", slug: "micro-tiny" },
  { prompt: "tiny anatomical heart with thin veins", slug: "single-needle" },
  { prompt: "metatron cube of nested polygons", slug: "geometric" },
  { prompt: "weathered rosary wrapped around clasped fingers", slug: "black-and-grey-realism" },
  { prompt: "third eye opening above arched brow", slug: "illustrative" },
  { prompt: "ancient coin talisman on braided cord", slug: "engraving-woodcut" },
  { prompt: "ouroboros circling a crescent moon", slug: "ornamental-filigree" },
  { prompt: "radiant sun with rayed geometric spokes", slug: "linework" },
  { prompt: "bold heart pierced by single dagger", slug: "american-traditional" },
  { prompt: "flaming sacred heart crowned with thorns", slug: "neo-traditional" },
  { prompt: "praying hands rising toward a star", slug: "sailor-jerry" },
  { prompt: "ornate crucifix draped in lilies", slug: "neo-traditional" },
  { prompt: "om symbol dissolving into lotus petals", slug: "watercolor" },
  { prompt: "evil eye shattering into glass shards", slug: "trash-polka" },
  { prompt: "geometric mandala blooming from center point", slug: "mandala" },
  { prompt: "delicate hamsa hand with hanging charms", slug: "fine-line" },
  { prompt: "tiny cross between two small stars", slug: "celestial-astro" },
  { prompt: "hands holding a glowing tarot card", slug: "illustrative" },
  { prompt: "serpent coiled around an ankh", slug: "blackwork" },
  { prompt: "lifelike eye with reflected window light", slug: "realism" },
  { prompt: "minimalist heartbeat line into heart", slug: "minimalist" },
  { prompt: "protective triangle eye shedding single tear", slug: "sketch-scribble" },
  { prompt: "interwoven runes forming a binding sigil", slug: "cyber-sigilism" },
  { prompt: "stippled mandala of overlapping lotus rings", slug: "dotwork-stippling" },
  { prompt: "two koi forming a yin yang", slug: "japanese-irezumi" },
  { prompt: "weeping eye held in cupped hands", slug: "surrealism" },
  { prompt: "small key talisman on slender chain", slug: "micro-tiny" },
  { prompt: "cross woven from endless looping knots", slug: "ornamental-filigree" },
  { prompt: "radiant chakra wheel spinning with petals", slug: "mandala" },
  { prompt: "evil eye nested in palm lines", slug: "single-needle" },
  { prompt: "glitching all-seeing eye with scan lines", slug: "glitch" },
  { prompt: "hand pinching a tiny burning candle", slug: "fine-line" },
  { prompt: "heart wrapped in barbed wire", slug: "blackwork" },
  { prompt: "ouroboros forming an infinity symbol", slug: "minimalist" },
  { prompt: "praying skeleton hands beneath rosary beads", slug: "chicano-fineline-bng" },
  { prompt: "seed pattern of overlapping concentric circles", slug: "linework" },
  { prompt: "winged heart ascending through clouds", slug: "american-traditional" },
  { prompt: "crescent moon cradling a single eye", slug: "celestial-astro" },
  { prompt: "stippled hamsa filled with tiny dots", slug: "dotwork-stippling" },
  { prompt: "cross formed from blooming wildflowers", slug: "floral-botanical" },
  { prompt: "open lotus releasing a rising soul", slug: "watercolor" },
  { prompt: "geometric wolf head inside sacred polygons", slug: "geometric" },
  { prompt: "talisman amulet engraved with old symbols", slug: "engraving-woodcut" },
  { prompt: "two hands forming heart against light", slug: "minimalist" },
  { prompt: "ornate evil eye framed with filigree", slug: "ornamental-filigree" },
  { prompt: "third eye glowing on a moth", slug: "illustrative" },
  { prompt: "serpent eating its tail around skull", slug: "neo-traditional" },
  { prompt: "tiny dotted cross behind the ear", slug: "stick-and-poke" },
  { prompt: "woman's profile dissolving into songbirds", slug: "fine-line" },
  { prompt: "mother cradling a sleeping newborn", slug: "black-and-grey-realism" },
  { prompt: "two lovers sharing one heartbeat", slug: "illustrative" },
  { prompt: "weathered grandfather's smiling face", slug: "portrait" },
  { prompt: "ballerina mid-pirouette on pointe", slug: "fine-line" },
  { prompt: "Greek marble bust with cracked cheek", slug: "black-and-grey-realism" },
  { prompt: "clasped praying hands releasing light", slug: "realism" },
  { prompt: "flamenco dancer's twisting silhouette", slug: "linework" },
  { prompt: "geisha glancing over her shoulder", slug: "japanese-irezumi" },
  { prompt: "tiny faceless figure walking alone", slug: "micro-tiny" },
  { prompt: "two profiles forming a single vase", slug: "minimalist" },
  { prompt: "crowned queen with closed eyes", slug: "neo-traditional" },
  { prompt: "old sailor's tattooed grizzled face", slug: "american-traditional" },
  { prompt: "child reaching toward parent's open hand", slug: "single-needle" },
  { prompt: "veiled widow lowering her eyes", slug: "black-and-grey-realism" },
  { prompt: "tribal warrior chief in full headdress", slug: "polynesian" },
  { prompt: "Maori ancestor face with carved spirals", slug: "maori-ta-moko" },
  { prompt: "weeping angel statue covering its face", slug: "realism" },
  { prompt: "couple embracing under falling petals", slug: "watercolor" },
  { prompt: "skeleton lovers slow-dancing in moonlight", slug: "neo-traditional" },
  { prompt: "monk meditating in lotus posture", slug: "dotwork-stippling" },
  { prompt: "Frida-style woman with floral crown", slug: "chicano-fineline-bng" },
  { prompt: "boxer's bruised face mid-roar", slug: "realism" },
  { prompt: "saint with halo and folded hands", slug: "engraving-woodcut" },
  { prompt: "faceless figure made of geometric shards", slug: "geometric" },
  { prompt: "twin sisters back to back", slug: "linework" },
  { prompt: "outstretched hand catching a single raindrop", slug: "single-needle" },
  { prompt: "Venus de Milo armless torso", slug: "black-and-grey-realism" },
  { prompt: "screaming face split in halves", slug: "trash-polka" },
  { prompt: "tribal mask of stacked sharp patterns", slug: "blackwork" },
  { prompt: "astronaut's reflective visor hiding a face", slug: "realism" },
  { prompt: "woman's face glitching into pixels", slug: "glitch" },
  { prompt: "old woman's hands knitting wool", slug: "black-and-grey-realism" },
  { prompt: "tango couple locked in a dip", slug: "illustrative" },
  { prompt: "child's silhouette chasing a kite", slug: "minimalist" },
  { prompt: "samurai face beneath horned helmet", slug: "japanese-irezumi" },
  { prompt: "goddess face surrounded by symmetrical petals", slug: "mandala" },
  { prompt: "newborn's tiny gripping fist", slug: "micro-tiny" },
  { prompt: "lovers kissing beneath an umbrella", slug: "sketch-scribble" },
  { prompt: "lady's face wrapped in flowing ribbon", slug: "ornamental-filigree" },
  { prompt: "raised fist breaking through chains", slug: "blackwork" },
  { prompt: "ghostly bride drifting through fog", slug: "surrealism" },
  { prompt: "girl blowing dandelion seeds away", slug: "fine-line" },
  { prompt: "stern emperor's profile facing left", slug: "roman-numerals" },
  { prompt: "two hands forming a heart shape", slug: "ignorant-style" },
  { prompt: "thinker statue resting on his fist", slug: "black-and-grey-realism" },
  { prompt: "woman's face merging with crescent moon", slug: "celestial-astro" },
  { prompt: "punk girl with mohawk snarling", slug: "new-school" },
  { prompt: "father lifting child above his shoulders", slug: "illustrative" },
  { prompt: "veiled dancer spinning trailing fabric", slug: "watercolor" },
  { prompt: "muscular figure fused with mechanical joints", slug: "biomechanical" },
  { prompt: "elder's face carved in deep wrinkles", slug: "portrait" },
  { prompt: "lovers' initials inside a banner", slug: "script-lettering" },
  { prompt: "hooded mourner kneeling at a grave", slug: "gothic-blackletter" },
  { prompt: "woman's portrait dripping rainbow pigment", slug: "watercolor" },
  { prompt: "graffiti b-boy frozen mid-freeze pose", slug: "graffiti" },
  { prompt: "a horned demon skull wreathed in flame", slug: "blackwork" },
  { prompt: "grim reaper drifting through a foggy graveyard", slug: "black-and-grey-realism" },
  { prompt: "a coiled serpent piercing a blooming rose", slug: "american-traditional" },
  { prompt: "a death's-head moth before a full moon", slug: "dotwork-stippling" },
  { prompt: "a crumbling gothic cathedral under a stormy sky", slug: "engraving-woodcut" },
  { prompt: "an occult sigil ringed with burning candles", slug: "cyber-sigilism" },
  { prompt: "a skeletal hand clutching a wilted rose", slug: "fine-line" },
  { prompt: "a screaming skull split by a lightning bolt", slug: "trash-polka" },
  { prompt: "a winged demon perched on a tombstone", slug: "neo-traditional" },
  { prompt: "a horned ram skull inside a pentagram", slug: "geometric" },
  { prompt: "a hooded reaper raising a curved scythe", slug: "blackwork" },
  { prompt: "a venomous snake slithering through a human skull", slug: "japanese-irezumi" },
  { prompt: "a luna moth with skull-marked wings", slug: "single-needle" },
  { prompt: "a crescent moon cradling a tiny skull", slug: "micro-tiny" },
  { prompt: "an inverted cross dripping with thorns", slug: "ignorant-style" },
  { prompt: "a possessed doll with cracked porcelain face", slug: "new-school" },
  { prompt: "a goat-headed demon throned in shadow", slug: "realism" },
  { prompt: "a skeleton lovers embracing beneath the moon", slug: "illustrative" },
  { prompt: "an all-seeing eye crowned with serpents", slug: "ornamental-filigree" },
  { prompt: "a bat soaring across a blood moon", slug: "linework" },
  { prompt: "a flaming sacred heart pierced by daggers", slug: "sailor-jerry" },
  { prompt: "a raven perched on a weathered skull", slug: "black-and-grey-realism" },
  { prompt: "a melting candle atop a grinning skull", slug: "neo-traditional" },
  { prompt: "a cobra rising from a coffin of roses", slug: "japanese-irezumi" },
  { prompt: "a horned skull mandala of bones and thorns", slug: "mandala" },
  { prompt: "a spectral hand reaching from a grave", slug: "sketch-scribble" },
  { prompt: "a goat skull glitching into static fragments", slug: "glitch" },
  { prompt: "a haunted forest devouring a lone cottage", slug: "watercolor" },
  { prompt: "a snake devouring its own tail in flames", slug: "blackwork" },
  { prompt: "a skull with butterfly wings and roses", slug: "fine-line" },
  { prompt: "a cloaked figure carrying a swinging lantern", slug: "illustrative" },
  { prompt: "an antlered forest demon with hollow eyes", slug: "surrealism" },
  { prompt: "a dagger plunged through a rose and snake", slug: "chicano-fineline-bng" },
  { prompt: "a skeletal angel weeping over a tomb", slug: "black-and-grey-realism" },
  { prompt: "a spider crawling across a crescent moon", slug: "micro-tiny" },
  { prompt: "a horned baphomet seated within a circle", slug: "dotwork-stippling" },
  { prompt: "a vampire bat clutching a tiny skull", slug: "american-traditional" },
  { prompt: "a wolf skull adorned with feathers and beads", slug: "neo-traditional" },
  { prompt: "an ouija planchette over a cursed alphabet", slug: "ignorant-style" },
  { prompt: "a phrase memento mori in gothic script", slug: "gothic-blackletter" },
  { prompt: "a skeleton playing a mournful violin", slug: "engraving-woodcut" },
  { prompt: "a serpent twined around a dripping dagger", slug: "single-needle" },
  { prompt: "a screaming ghost trapped in barbed wire", slug: "trash-polka" },
  { prompt: "a horned skull crowned with rose thorns", slug: "minimalist" },
  { prompt: "a black cat arched before a glowing moon", slug: "linework" },
  { prompt: "a decaying hand rising through cracked earth", slug: "realism" },
  { prompt: "a moth circling a flickering gothic lantern", slug: "stick-and-poke" },
  { prompt: "a demonic gargoyle perched on a spire", slug: "3d-realism" },
  { prompt: "a coiled viper guarding a pile of bones", slug: "polynesian" },
  { prompt: "a tarot death card with riding skeleton", slug: "illustrative" },
  { prompt: "a crow skull pierced by a single nail", slug: "ignorant-style" },
  { prompt: "a phrase forever damned in flowing letters", slug: "calligraphy" },
  { prompt: "a skull eclipsed by a ringed planet", slug: "celestial-astro" },
  { prompt: "a chained demon breaking free of its bonds", slug: "biomechanical" },
  { prompt: "a snake coiled through an empty rib cage", slug: "abstract" },
  { prompt: "snow-capped mountain peak above pine treeline", slug: "linework" },
  { prompt: "cresting ocean wave curling into foam", slug: "japanese-irezumi" },
  { prompt: "dense pine forest fading into mist", slug: "fine-line" },
  { prompt: "lone saguaro cactus in desert dusk", slug: "single-needle" },
  { prompt: "winding river through a narrow canyon", slug: "minimalist" },
  { prompt: "sun sinking below the horizon line", slug: "micro-tiny" },
  { prompt: "lightning splitting a black storm cloud", slug: "blackwork" },
  { prompt: "waterfall plunging over a mossy cliff", slug: "realism" },
  { prompt: "lighthouse beam sweeping over crashing surf", slug: "neo-traditional" },
  { prompt: "crackling campfire under a starry night", slug: "illustrative" },
  { prompt: "three triangular mountain peaks in a row", slug: "geometric" },
  { prompt: "great wave with curling tendrils of spray", slug: "japanese-irezumi" },
  { prompt: "single pine tree on a rocky island", slug: "minimalist" },
  { prompt: "rolling sand dunes under a low sun", slug: "dotwork-stippling" },
  { prompt: "river delta branching toward the sea", slug: "linework" },
  { prompt: "layered sunset over distant rolling hills", slug: "watercolor" },
  { prompt: "thunderhead towering over open plains", slug: "black-and-grey-realism" },
  { prompt: "cascading waterfall framed by fern leaves", slug: "fine-line" },
  { prompt: "weathered lighthouse on a stormy cliff", slug: "american-traditional" },
  { prompt: "campfire flames with drifting orange embers", slug: "neo-traditional" },
  { prompt: "mountain range reflected in a still lake", slug: "sketch-scribble" },
  { prompt: "breaking wave beneath a crescent moon", slug: "celestial-astro" },
  { prompt: "redwood forest canopy seen from below", slug: "realism" },
  { prompt: "desert mesa silhouette at golden hour", slug: "minimalist" },
  { prompt: "rushing mountain stream over smooth stones", slug: "engraving-woodcut" },
  { prompt: "sun rays bursting through parting clouds", slug: "dotwork-stippling" },
  { prompt: "spiral storm cloud swallowing the sky", slug: "surrealism" },
  { prompt: "twin waterfalls flanked by jagged rocks", slug: "japanese-irezumi" },
  { prompt: "lighthouse keeper's lamp glowing in fog", slug: "black-and-grey-realism" },
  { prompt: "campfire ring under towering evergreens", slug: "linework" },
  { prompt: "alpine peak ringed by a halo of stars", slug: "celestial-astro" },
  { prompt: "tidal wave colliding with coastal cliffs", slug: "trash-polka" },
  { prompt: "fir tree silhouette inside a circle", slug: "micro-tiny" },
  { prompt: "cactus blossom opening in arid heat", slug: "floral-botanical" },
  { prompt: "meandering river map carved in valleys", slug: "ornamental-filigree" },
  { prompt: "blazing sunset radiating concentric rings", slug: "mandala" },
  { prompt: "hailstorm hammering a windswept ridge", slug: "ignorant-style" },
  { prompt: "waterfall mist catching a faint rainbow", slug: "watercolor" },
  { prompt: "lighthouse on a tiny rocky outcrop", slug: "micro-tiny" },
  { prompt: "lone hiker beside a glowing campfire", slug: "illustrative" },
  { prompt: "jagged mountain skyline against full moon", slug: "blackwork" },
  { prompt: "ocean swell rolling toward a quiet shore", slug: "fine-line" },
  { prompt: "forest path disappearing into shadows", slug: "sketch-scribble" },
  { prompt: "desert canyon walls layered in strata", slug: "engraving-woodcut" },
  { prompt: "river current swirling around boulders", slug: "abstract" },
  { prompt: "setting sun framed by palm fronds", slug: "single-needle" },
  { prompt: "storm waves under a flickering sky", slug: "cyber-sigilism" },
  { prompt: "cascading falls inside a hexagon frame", slug: "geometric" },
  { prompt: "lighthouse and seagull above rough seas", slug: "sailor-jerry" },
  { prompt: "campfire smoke curling into night air", slug: "minimalist" },
  { prompt: "majestic mountain with cascading glacier", slug: "realism" },
  { prompt: "wave breaking over a koi-filled tide", slug: "japanese-irezumi" },
  { prompt: "pine forest framed in an oval portal", slug: "ornamental-filigree" },
  { prompt: "moonlit desert with distant coyote howl", slug: "black-and-grey-realism" },
  { prompt: "waterfall feeding a glowing forest pool", slug: "watercolor" },
  { prompt: "two cherries sharing one stem", slug: "fine-line" },
  { prompt: "a steaming bowl of ramen noodles", slug: "illustrative" },
  { prompt: "tiny ghost holding a single balloon", slug: "micro-tiny" },
  { prompt: "chunky retro game controller buttons", slug: "new-school" },
  { prompt: "smiling slice of strawberry shortcake", slug: "neo-traditional" },
  { prompt: "a wide-eyed cartoon cat waving", slug: "anime-manga" },
  { prompt: "stack of pixel hearts floating upward", slug: "minimalist" },
  { prompt: "little robot with antenna and treads", slug: "linework" },
  { prompt: "a winking star sticker outline", slug: "single-needle" },
  { prompt: "puffy cloud with a happy face", slug: "stick-and-poke" },
  { prompt: "boba tea cup with bouncing pearls", slug: "illustrative" },
  { prompt: "tiny dinosaur munching a leaf", slug: "micro-tiny" },
  { prompt: "melting ice cream cone dripping rainbow", slug: "watercolor" },
  { prompt: "chubby bee carrying a honey jar", slug: "fine-line" },
  { prompt: "retro flip phone with hearts onscreen", slug: "new-school" },
  { prompt: "a sleepy crescent moon with closed eyes", slug: "minimalist" },
  { prompt: "spinning vinyl record with sparkles", slug: "illustrative" },
  { prompt: "tiny mushroom with polka dot cap", slug: "dotwork-stippling" },
  { prompt: "a winged heart with a little crown", slug: "american-traditional" },
  { prompt: "fortune cookie cracking open a wish", slug: "fine-line" },
  { prompt: "blocky video game power-up coin", slug: "ignorant-style" },
  { prompt: "a duckling wearing tiny rain boots", slug: "single-needle" },
  { prompt: "fluffy cloud raining little stars", slug: "celestial-astro" },
  { prompt: "a frog perched on a lily pad", slug: "linework" },
];
